name: kalemat Bot Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: kalemat-bot-group
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm install --no-audit --no-fund

      - name: Run Bot
        env:
          U_MAIL_1: ${{ secrets.U_MAIL_1 }}
          U_PASS_1: ${{ secrets.U_PASS_1 }}
        run: node index.js
