name: WOLFdle Auto Player

on:
  schedule:
    - cron: '0 0 * * *' # يعمل تلقائياً كل يوم منتصف الليل
  workflow_dispatch: # زر التشغيل اليدوي

jobs:
  play-game:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 سحب الكود من المستودع
        uses: actions/checkout@v4

      - name: 🟢 إعداد نود جي إس
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 تثبيت المكتبات وتخطي سكربتات البناء المزعجة
        # أمر --ignore-scripts هو الحل السحري لتخطي فشل بناء مكتبة wrtc للصوت
        run: npm install --ignore-scripts --no-audit --no-fund

      - name: 🚀 إطلاق البوت
        env:
          U_MAIL_1: ${{ secrets.U_MAIL_1 }}
          U_PASS_1: ${{ secrets.U_PASS_1 }}
        run: npm start
