name: WOLFdle Auto Player

on:
  schedule:
    - cron: '0 0 * * *' # ينطلق تلقائياً كل يوم منتصف الليل
  workflow_dispatch: # زر التشغيل اليدوي للتجربة في أي وقت

jobs:
  play-game:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 سحب الكود
        uses: actions/checkout@v4

      - name: 🟢 إعداد نود جي إس
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 تثبيت المكتبات
        run: npm install

      - name: 🚀 إطلاق البوت
        env:
          U_MAIL_1: ${{ secrets.U_MAIL_1 }}
          U_PASS_1: ${{ secrets.U_PASS_1 }}
        run: npm start
